### ISSUE TITLE
Cannot allocate memory during generating project for qt-creator

### ISSUE THREAD

**Issue by woyaru** [BobBuildTool/bob#113]
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Traceback (most recent call last):
  File "/home/user/BobBuildTool/pym/bob/scripts.py", line 114, in bob
    availableCommands[verb][1](argv, bobRoot)
  File "/home/user/BobBuildTool/pym/bob/scripts.py", line 52, in __project
    doProject(*args, **kwargs)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 998, in doProject
    doDevelop(devArgs, bobRoot)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 903, in doDevelop
    commonBuildDevelop(parser, argv, bobRoot, True)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 876, in commonBuildDevelop
    builder.cook([p], p.getPackage(), args.checkout_only)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 504, in cook
    self._cookPackageStep(step, checkoutOnly, depth)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 725, in _cookPackageStep
    checkoutOnly, depth+1)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 501, in cook
    self._cookBuildStep(step, checkoutOnly, depth)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 614, in _cookBuildStep
    checkoutOnly, depth+1)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 504, in cook
    self._cookPackageStep(step, checkoutOnly, depth)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 725, in _cookPackageStep
    checkoutOnly, depth+1)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 501, in cook
    self._cookBuildStep(step, checkoutOnly, depth)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 614, in _cookBuildStep
    checkoutOnly, depth+1)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 498, in cook
    self._cookCheckoutStep(step, depth)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 588, in _cookCheckoutStep
    self._runShell(checkoutStep, "checkout")
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 463, in _runShell
    proc = subprocess.Popen(cmdLine, cwd=step.getWorkspacePath(), env=runEnv)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1395, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory

**Comment by jkloetzke** [comment]
Looks like you didn't have enough memory left. What version of Bob are you using?

The only thing that could be done here is to catch the error and abort the build in a proper way...

**Comment by rhubert** [comment]
Was this happening while working with QtCreator?
There are some memory leaks in QtCreator which will consume all of you memory after a while...
[QT-Bugtracker](https://bugreports.qt.io/browse/QTBUG-21298?jql=project%20in%20%28QTCREATORBUG%2C%20QTBUG%29%20AND%20status%20in%20%28Open%2C%20%22In%20Progress%22%2C%20Reopened%29%20AND%20text%20~%20leak)

I observed this some time ago - can you please monitor the memory usage of QtCreator and/or how much free memory is available on your system before starting bob?

@jkloetzke : We should also print the bob version in the exception handler...

**Comment by jkloetzke** [comment]
@woyaru I've closed the isse with the fix in Bob to handle the OOM situation gracefully. I don't think there is much more that we can do in Bob. Feel free to reopen if you think the problem was caused by Bob in the first place.
