### ISSUE TITLE
scmOverrides no longer working

### ISSUE THREAD

**Issue by Kalabaza** [BobBuildTool/bob#119]
I'm getting this error with the latest release of Bob when using scmOverrides on a user.yaml file:

An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.11.0-60-gd33758a
Traceback (most recent call last):
  File "/home/user/BobBuildTool/pym/bob/scripts.py", line 100, in catchErrors
    ret = fun(*args, **kwargs)
  File "/home/user/BobBuildTool/pym/bob/scripts.py", line 140, in cmd
    availableCommands[verb][1](argv, bobRoot)
  File "/home/user/BobBuildTool/pym/bob/scripts.py", line 32, in __develop
    doDevelop(*args, **kwargs)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 1012, in doDevelop
    commonBuildDevelop(parser, argv, bobRoot, True)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 974, in commonBuildDevelop
    builder.cook([p], p.getPackage(), args.checkout_only)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 538, in cook
    self._cookPackageStep(step, checkoutOnly, depth)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 745, in _cookPackageStep
    packageBuildId = self._getBuildId(packageStep, depth)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 856, in _getBuildId
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/home/user/BobBuildTool/pym/bob/input.py", line 908, in getDigest
    d = calculate(arg)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 856, in <lambda>
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 856, in _getBuildId
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/home/user/BobBuildTool/pym/bob/input.py", line 908, in getDigest
    d = calculate(arg)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 856, in <lambda>
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 852, in _getBuildId
    self.cook([step], step.getPackage(), depth)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 532, in cook
    self._cookCheckoutStep(step, depth)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 553, in _cookCheckoutStep
    overrides.update(scm.getActiveOverrides())
  File "/home/user/BobBuildTool/pym/bob/scm/scm.py", line 48, in __hash__
    frozenset(self.__set.items()), frozenset(self.__replaceRaw.items())))
TypeError: unhashable type: 'dict'

**Comment by rhubert** [comment]
Unit tests are passing and I can't reproduce this... can you please give some additional informations?

**Comment by Kalabaza** [comment]
That error is when the user.yaml file is being used to override a url on a recipe, this is a sample file:

scmOverrides:
   -
      match:
         url: "www.oldurl.com"
      replace:
         url:
            pattern: "www.oldurl.com"
            replacement: "www.newurl.com"

**Comment by rhubert** [comment]
Thanks - can reproduce this now. You can use 
```
match:
  url: "www.oldurl.com"
set:
  url: "www.newurl.com"
```
as a temporary workaround.
