### ISSUE TITLE
Crash in shell archive backend

### ISSUE THREAD

**Issue by jkloetzke** [BobBuildTool/bob#140]
```
   UPLOAD    work/sandbox/debian-jessie-x86_64/dist/1/workspace to d1/69/3b781f1fb99d2e1bda1c04a7a511e4f1ae5d-1.tgz
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.12.1
Traceback (most recent call last):
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/scripts.py", line 109, in catchErrors
    ret = fun(*args, **kwargs)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/scripts.py", line 180, in cmd
    availableCommands[args.command][1](args.args, bobRoot)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/scripts.py", line 29, in __build
    doBuild(*args, **kwargs)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 1032, in doBuild
    commonBuildDevelop(parser, argv, bobRoot, False)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 998, in commonBuildDevelop
    builder.cook([p], p.getPackage(), args.checkout_only)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 558, in cook
    self._cookPackageStep(step, checkoutOnly, depth)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 767, in _cookPackageStep
    packageBuildId = self._getBuildId(packageStep, depth)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 879, in _getBuildId
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/input.py", line 908, in getDigest
    d = calculate(arg)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 879, in <lambda>
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 879, in _getBuildId
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/input.py", line 908, in getDigest
    d = calculate(arg)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 879, in <lambda>
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 875, in _getBuildId
    self.cook([step], step.getPackage(), depth)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 552, in cook
    self._cookCheckoutStep(step, depth)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 585, in _cookCheckoutStep
    False, depth+1)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 558, in cook
    self._cookPackageStep(step, checkoutOnly, depth)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/cmds/build.py", line 853, in _cookPackageStep
    self.__archive.uploadPackage(packageBuildId, audit, prettyPackagePath, self.__verbose)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/archive.py", line 595, in uploadPackage
    i.uploadPackage(buildId, audit, content, verbose)
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/archive.py", line 192, in uploadPackage
    tar.add(content, arcname="content")
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/archive.py", line 556, in __exit__
    env = { k:v for (k,v) in os.environ.items() if k in self.__whiteList }
  File "/opt/lvmvol/quellen/BobBuildTool/pym/bob/archive.py", line 556, in <dictcomp>
    env = { k:v for (k,v) in os.environ.items() if k in self.__whiteList }
AttributeError: 'CustomUploader' object has no attribute '_CustomUploader__whiteList'
```

**Comment by rhubert** [comment]
archive.py 473: 
```python
        if verbose > 0:
            print(colorize("   DOWNLOAD  {} from {} ({}) ...".format(path, url, tmpName), "32"), end="")
        else:
            print(colorize("   DOWNLOAD  {}...".format(path), "32"), end="")
```
verbose & path not defined.  these prints can be removed...
