### ISSUE TITLE
ImportError: No module named 'pyparsing'

### ISSUE THREAD

**Issue by rhubert** [BobBuildTool/bob#146]
```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/hubert/projects/bob/pym/bob/scripts.py", line 19, in <module>
    from .input import RecipeSet
  File "/home/hubert/projects/bob/pym/bob/input.py", line 19, in <module>
    from .pathspec import PackageSet
  File "/home/hubert/projects/bob/pym/bob/pathspec.py", line 25, in <module>
    import pyparsing
ImportError: No module named 'pyparsing'
```

**Comment by jkloetzke** [comment]
Closed with 39400c2.
