### ISSUE TITLE
plugins not working cause properties hash is empty

### ISSUE THREAD

**Issue by kolewu** [BobBuildTool/bob#148]
Plugins are not working in current master:

```sh
mkdir -p mytest/{recipes,plugins}
cp contrib/plugins/path-fmt.py mytest/plugins/
cp test/single/recipes/root.yaml mytest/recipes/
cat > mytest/config.yaml <<EOF
bobMinimumVersion: "0.3"

plugins:
    - path-fmt
EOF

cd mytest
../bob ls
```
The first commit that shows the error is 6af52e7 and the error there is this
```
WARNING: relativeIncludes policy not set. Using recipes directory as base for all includes!
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.12.0-43-g6af52e7
Traceback (most recent call last):
  File "bob/pym/bob/scripts.py", line 115, in catchErrors
    ret = fun(*args, **kwargs)
  File "bob/pym/bob/scripts.py", line 195, in cmd
    availableCommands[args.command][1](args.args, bobRoot)
  File "bob/pym/bob/scripts.py", line 54, in __ls
    doLS(*args, **kwargs)
  File "bob/pym/bob/cmds/misc.py", line 109, in doLS
    for (stack, root) in packages.walkTreePath(args.package):
  File "bob/pym/bob/pathspec.py", line 209, in walkTreePath
    root = self.__getGraphRoot()
  File "bob/pym/bob/pathspec.py", line 190, in __getGraphRoot
    root = self.getRootPackage()
  File "bob/pym/bob/pathspec.py", line 201, in getRootPackage
    self.__root = self.__generator()
  File "bob/pym/bob/input.py", line 2407, in <lambda>
    lambda: self.__generatePackages(nameFormatter, env, cacheKey, sandboxEnabled))
  File "bob/pym/bob/input.py", line 2389, in __generatePackages
    states)[0]
  File "bob/pym/bob/input.py", line 1647, in prepare
    for s in states.values(): s.onEnter(env, tools, self.__properties)
  File "plugins/path-fmt.py", line 39, in onEnter
    self.__checkoutDir = properties['checkoutDir'].getValue()
KeyError: 'checkoutDir'
```

When printing out the `properties` dict in the *onEnter* function of the plugin, it is empty.

**Comment by jkloetzke** [comment]
Thanks @kolewu for bisecting the issue and @rhubert for the quick fix. :+1:
