### ISSUE TITLE
Bob crashes in docker environment

### ISSUE THREAD

**Issue by rkollataj** [BobBuildTool/bob#171]
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.13.0-rc2
Traceback (most recent call last):
  File "/project/BobBuildTool/pym/bob/scripts.py", line 119, in catchErrors
    ret = fun(*args, **kwargs)
  File "/project/BobBuildTool/pym/bob/scripts.py", line 200, in cmd
    availableCommands[args.command][1](args.args, bobRoot)
  File "/project/BobBuildTool/pym/bob/scripts.py", line 37, in __develop
    doDevelop(*args, **kwargs)
  File "/project/BobBuildTool/pym/bob/cmds/build.py", line 1346, in doDevelop
    commonBuildDevelop(parser, argv, bobRoot, True)
  File "/project/BobBuildTool/pym/bob/cmds/build.py", line 1288, in commonBuildDevelop
    for package in packages.queryPackagePath(p):
  File "/project/BobBuildTool/pym/bob/pathspec.py", line 853, in queryPackagePath
    (nodes, valid) = self.__query(path)
  File "/project/BobBuildTool/pym/bob/pathspec.py", line 824, in __query
    return path[0].evalForward(self.__getGraphRoot())
  File "/project/BobBuildTool/pym/bob/pathspec.py", line 778, in __getGraphRoot
    self.__graph = PkgGraphNode.create(cacheName, self.__cacheKey, root)
  File "/project/BobBuildTool/pym/bob/pathspec.py", line 550, in create
    return cls(dbm.open(cacheName, 'r'), rootKey)
  File "/project/BobBuildTool/pym/bob/pathspec.py", line 524, in __init__
    (self.__name, self.__parents, self.__childs) = pickle.loads(db[key])
KeyError: b'\xa3\x13\x00\x00'

**Comment by rkollataj** [comment]
I have solved the issue by deleting repository and cloning it again. I suspect I might have had some wrong characters in user.yaml? That would be pretty strange as I was able to build on host machine and failing on docker. Anyway the problem is not existing any longer.

**Comment by jkloetzke** [comment]
That error is really strange and I currently have no idea how this can happen. Did you share the workspace between your host and docker?

**Comment by rkollataj** [comment]
Yes, the workspace (source code) is shared between host and docker. The
issue happened also today. Again I fixed it by downloading clean receipts
repo. I realise it may be hard to track the issue down. I think it may be
closed as I know the workaround.

16.11.2017 14:39 "Jan Klötzke" <notifications@github.com> napisał(a):

That error is really strange and I currently have no idea how this can
happen. Did you share the workspace between your host and docker?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BobBuildTool/bob/issues/171#issuecomment-344925018>,
or mute
the thread

**Comment by jkloetzke** [comment]
I'm afraid this setup is too brittle. Bob is relying on the Unix dbm key-value store and the library in the background does not work well with concurrent accesses. Closing it because I think Bob cannot do much to prevent this error...
