### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by jb090979** [BobBuildTool/bob#204]
>> zr3/zr3-variant-VW_EU/images::boot-device/images::boot-normal/carcom::tsd-carcom-mib3-image
   QUERY     sandbox::debian-stretch-x86_64 .. ok
   QUERY     toolchain::cmake .. ok
   QUERY     toolchain::lcov .. ok
   QUERY     toolchain::lcov2cobertura .. ok
   QUERY     system::ext-liblz4-tool .. unknown
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.13.1-rc2
Traceback (most recent call last):
  File "/home/user/BobBuildTool/pym/bob/scripts.py", line 119, in catchErrors
    ret = fun(*args, **kwargs)
  File "/home/user/BobBuildTool/pym/bob/scripts.py", line 200, in cmd
    availableCommands[args.command][1](args.args, bobRoot)
  File "/home/user/BobBuildTool/pym/bob/scripts.py", line 37, in __develop
    doDevelop(*args, **kwargs)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 1346, in doDevelop
    commonBuildDevelop(parser, argv, bobRoot, True)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 1303, in commonBuildDevelop
    builder.cook(p, True if args.build_mode == 'checkout-only' else False)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 639, in cook
    self._cook([step], step.getPackage(), checkoutOnly)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 673, in _cook
    self._cookPackageStep(step, checkoutOnly, depth)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 899, in _cookPackageStep
    packageBuildId = self._getBuildId(packageStep, depth)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 1114, in _getBuildId
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/home/user/BobBuildTool/pym/bob/input.py", line 622, in getDigest
    d = calculate(tool.step)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 1114, in <lambda>
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 1114, in _getBuildId
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/home/user/BobBuildTool/pym/bob/input.py", line 637, in getDigest
    d = calculate(arg)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 1114, in <lambda>
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 1114, in _getBuildId
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/home/user/BobBuildTool/pym/bob/input.py", line 637, in getDigest
    d = calculate(arg)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 1114, in <lambda>
    ret = step.getDigest(lambda s: self._getBuildId(s, depth+1), True)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 1108, in _getBuildId
    tmp = self.__getCheckoutStepBuildId(step, depth)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 1067, in __getCheckoutStepBuildId
    liveBId = self.__queryLiveBuildId(step)
  File "/home/user/BobBuildTool/pym/bob/cmds/build.py", line 1015, in __queryLiveBuildId
    liveBId = step.predictLiveBuildId()
  File "/home/user/BobBuildTool/pym/bob/input.py", line 971, in predictLiveBuildId
    for liveBId in s.predictLiveBuildId():
  File "/home/user/BobBuildTool/pym/bob/scm/git.py", line 370, in predictLiveBuildId
    stderr=subprocess.STDOUT).strip()
  File "/usr/lib/python3.4/subprocess.py", line 607, in check_output
    with Popen(*popenargs, stdout=PIPE, **kwargs) as process:
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1395, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory

**Comment by rhubert** [comment]
`OSError: [Errno 12] Cannot allocate memory`

-> Looks like you're running out of memory?

**Comment by jkloetzke** [comment]
You're out of memory. I would suggest to try the latest version because it has some performance improvements that should also lower the memory usage.

The fix for this bug would be to catch the error but the build would just fail with a proper error message.
