### ISSUE TITLE
bob project qt-creator: File name too long

### ISSUE THREAD

**Issue by anaxarsys** [BobBuildTool/bob#222]
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.13.0-126-g467f628
Traceback (most recent call last):
  File "/usr/lib/bob/pym/bob/scripts.py", line 120, in catchErrors
    ret = fun(*args, **kwargs)
  File "/usr/lib/bob/pym/bob/scripts.py", line 219, in cmd
    cmd(args.args, bobRoot)
  File "/usr/lib/bob/pym/bob/scripts.py", line 51, in __project
    doProject(*args, **kwargs)
  File "/usr/lib/bob/pym/bob/cmds/build.py", line 1616, in doProject
    generator(package, args.args, extra)
  File "/usr/lib/bob/pym/bob/generators/QtCreatorGenerator.py", line 208, in qtProjectGenerator
    os.makedirs(destination)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '\<very long auto-generated name\>'

===
Is it possible to customize a name of the generated project directory?

**Comment by rhubert** [comment]
Yes, have you read the manpage?
```
--destination DEST
--name NAME
```

might help you.
