### ISSUE TITLE
Error creating new Qt-Creator project

### ISSUE THREAD

**Issue by tzavellas** [BobBuildTool/bob#247]
Hi I got an error while creating a new qt-creator project with the following backtrace:

`Bob version 0.14.0-rc2
Traceback (most recent call last):
  File "/usr/local/lib/bob/pym/bob/scripts.py", line 120, in catchErrors
    ret = fun(*args, **kwargs)
  File "/usr/local/lib/bob/pym/bob/scripts.py", line 219, in cmd
    cmd(args.args, bobRoot)
  File "/usr/local/lib/bob/pym/bob/scripts.py", line 51, in __project
    doProject(*args, **kwargs)
  File "/usr/local/lib/bob/pym/bob/cmds/build.py", line 1599, in doProject
    generator(package, args.args, extra)
  File "/usr/local/lib/bob/pym/bob/generators/QtCreatorGenerator.py", line 194, in qtProjectGenerator
    excludes.append(re.compile(e))
  File "/usr/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0`

**Comment by rhubert** [comment]
What was the comandline to create the project?

**Comment by tzavellas** [comment]
`bob project -n qt-creator projectName --exclude "*.ext.*"`

**Comment by jkloetzke** [comment]
The `--exclude` option takes a regular expression. Your expression starts with `*` which is an invalid regex. Maybe you left out `--exclude` the 2nd time our unconsciously fixed the regex when tried it again?

Anyway, we should catch the error and print a proper error message.

**Comment by tzavellas** [comment]
Oh, ok I see! Then I must have written it correctly the second time, that is `bob project -n qt-creator projectName --exclude ".*ext.*"` and didn't see the difference with the two commands. Thanks for your reply!
