### ISSUE TITLE
bob project vs2019 crashs

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#254]
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.15.1-26-gac769eb
Traceback (most recent call last):
  File "/home/mhaase/bob/pym/bob/scripts.py", line 120, in catchErrors
    ret = fun(*args, **kwargs)
  File "/home/mhaase/bob/pym/bob/scripts.py", line 222, in cmd
    cmd(args.args, bobRoot)
  File "/home/mhaase/bob/pym/bob/scripts.py", line 51, in __project
    doProject(*args, **kwargs)
  File "/home/mhaase/bob/pym/bob/cmds/build/project.py", line 117, in doProject
    generator(package, args.args, extra)
  File "/home/mhaase/bob/pym/bob/generators/VisualStudio.py", line 330, in vs2019ProjectGenerator
    generator.generate(extra)
  File "/home/mhaase/bob/pym/bob/generators/VisualStudio.py", line 270, in generate
    for name,scan in self.packages.items()
  File "/home/mhaase/bob/pym/bob/generators/VisualStudio.py", line 270, in <dictcomp>
    for name,scan in self.packages.items()
  File "/home/mhaase/bob/pym/bob/generators/VisualStudio.py", line 141, in __init__
    self.workspacePath = recipesRoot.joinpath(PureWindowsPath(scan.workspacePath))
AttributeError: 'BaseScanner' object has no attribute 'workspacePath'

**Comment by mahaase** [comment]
i fixed it like this:

$ git diff
diff --git a/pym/bob/generators/common.py b/pym/bob/generators/common.py
index 680dceb..50be5a6 100644
--- a/pym/bob/generators/common.py
+++ b/pym/bob/generators/common.py
@@ -52,6 +52,7 @@ class BaseScanner:
         self.__resources = set()
         self.__incPaths = set()
         self.__dependencies = set()
+        self.workspacePath = ''

     def _addFile(self, root, fileName):
         added = True
