### ISSUE TITLE
variable substition not working

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#259]
$ bob ls

An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.15.1-37-geabc74a
Traceback (most recent call last):
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/scripts.py", line 120, in catchErrors
    ret = fun(*args, **kwargs)
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/scripts.py", line 222, in cmd
    cmd(args.args, bobRoot)
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/scripts.py", line 47, in __ls
    doLS(*args, **kwargs)
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/cmds/misc.py", line 104, in doLS
    for (stack, root) in packages.queryTreePath(args.package):
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/pathspec.py", line 852, in queryTreePath
    (nodes, valid) = self.__query(path)
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/pathspec.py", line 829, in __query
    root = self.__getGraphRoot()
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/pathspec.py", line 781, in __getGraphRoot
    self.getRootPackage)
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/pathspec.py", line 535, in init
    root = PkgGraphNode.__convertPackageToGraph(db, rootGenerator())
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/pathspec.py", line 843, in getRootPackage
    self.__root = self.__generator()
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/input.py", line 3241, in <lambda>
    lambda: self.__generatePackages(nameFormatter, env, cacheKey, sandboxEnabled))
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/input.py", line 3224, in __generatePackages
    result = self.__rootRecipe.prepare(env, sandboxEnabled, states)[0]
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/input.py", line 2193, in prepare
    depStack)
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/input.py", line 2256, in prepare
    for d in depCoreStep.providedDeps)
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/input.py", line 1735, in extend
    for i in gen: self.append(i)
  File "/mnt/c/msys64-1/home/mhaase/bob/pym/bob/input.py", line 1732, in append
    self.errorHandler(name, stack + ref.refGetStack(), stack + ref2.refGetStack())
NameError: name 'stack' is not defined

recipe:
depends:
    -
        if: "${UNUSED_VARIABLE:-}"
        depends:

The problem is the ":-" inside of "${}".

UPDATE: seems a general issue... also not working in environment: 

environment:
    TEST: "${UNUSED_VARIABLE:-}"

**Comment by jkloetzke** [comment]
The crash is in an error handling path of Bob. It looks like your recipes have provided dependencies that are incompatible. But instead of printing a proper error message Bob crashes. It has nothing really to do with variable substitution.

**Comment by mahaase** [comment]
now I got the issue message by bob 👍
