### ISSUE TITLE
bob crash in bob _invoke?

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#311]
Hey, I get the following issue on jenkins slave. No idea if that relates to the issues, that it occurs on slave?!

```
+ bob _invoke toolchain_cmake-win64_src_1-e6b5-398d.spec.json -vv
+ <wget> http://fdt-c-pcs-0004.fdtech.intern/fileserver/cmake-3.15.0-win64-x64.zip > ./cmake-3.15.0-win64-x64.zip
Error: Recipe toolchain::cmake-win64 in checkoutSCM: dir:., url:http://fdt-c-pcs-0004.fdtech.intern/fileserver/cmake-3.15.0-win64-x64.zip in checkoutSCM: dir:., url:http://fdt-c-pcs-0004.fdtech.intern/fileserver/cmake-3.15.0-win64-x64.zip failed
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.16.1.dev94+gd2f778e
Traceback (most recent call last):
  File "/c/Local/bob/pym/bob/scm/url.py", line 275, in invoke
    err = await loop.run_in_executor(None, UrlScm._download, self, destination)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/c/Local/bob/pym/bob/scm/url.py", line 207, in _download
    signal.signal(signal.SIGINT, signal.SIG_DFL)
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/c/Local/bob/pym/bob/scripts.py", line 141, in catchErrors
    ret = fun(*args, **kwargs)
  File "/c/Local/bob/pym/bob/scripts.py", line 242, in cmd
    ret = cmd(args.args, bobRoot)
  File "/c/Local/bob/pym/bob/scripts.py", line 99, in __invoke
    return doInvoke(*args, **kwargs)
  File "/c/Local/bob/pym/bob/cmds/invoke.py", line 64, in doInvoke
    args.clean, args.keep_sandbox))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/c/Local/bob/pym/bob/invoker.py", line 340, in executeStep
    await scm.invoke(self)
  File "/c/Local/bob/pym/bob/scm/url.py", line 278, in invoke
    except (concurrent.futures.CancelledError, concurrent.futures.process.BrokenProcessPool):
  File "/usr/lib/python3.7/concurrent/futures/__init__.py", line 52, in __getattr__
    raise AttributeError(f"module {__name__} has no attribute {name}")
AttributeError: module concurrent.futures has no attribute process
Build step 'Shell ausführen' marked build as failure
```

**Comment by mahaase** [comment]
I googled, that this is a changed behavior in python version.
BUT i have installed on bath machines py3.7.4, in master the issue doesn't occurs...?!
If I comment this out, it is running again.

**Comment by jkloetzke** [comment]
The line with `signal.signal(signal.SIGINT, signal.SIG_DFL)` was added only recently. I guess the problem is that the asyncio executor setup differs between `bob build/dev` and `bob _invoke`. Looks easy...

**Comment by mahaase** [comment]
like this?

```
diff --git a/pym/bob/scm/url.py b/pym/bob/scm/url.py
index 729ba2c..176c29c 100644
--- a/pym/bob/scm/url.py
+++ b/pym/bob/scm/url.py
@@ -204,7 +204,8 @@ class UrlScm(Scm):
 
     def _download(self, destination):
         # restore signals to default so that Ctrl+C kills us
-        signal.signal(signal.SIGINT, signal.SIG_DFL)
+        if threading.current_thread() == threading.main_thread():
+            signal.signal(signal.SIGINT, signal.SIG_DFL)
 
         headers = {}
         context = None if self.__sslVerify else ssl.SSLContext(ssl.PROTOCOL_SSLv23)
```
