### ISSUE TITLE
dbm.error: db type is dbm.gnu, but the module is not available

### ISSUE THREAD

**Issue by Djultypremierdunom** [BobBuildTool/bob#326]
Hi,

I'm on OS 10.7.5, working on a website with Nikola 8 in a virtualenv. 
Newly updated, I had to upgrade a bunch of things. But at the very moment of truth and delightful enjoyment of building the site, terminal returns this :

(nikola_env) julien:nikola annebitran$ nikola build
[2020-04-29T17:30:36Z] WARNING: Nikola: The UNSLUGIFY_TITLES setting was renamed to FILE_METADATA_UNSLUGIFY_TITLES.
[2020-04-29T17:30:36Z] WARNING: Nikola: The TAG_PAGES_DESCRIPTIONS setting was renamed to TAG_DESCRIPTIONS.
Scanning posts.done!
Traceback (most recent call last):
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/dependency.py", line 156, in __init__
    self._dbm = ddbm.open(self.name, 'c')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/dbm/__init__.py", line 91, in open
    "available".format(result))
dbm.error: db type is dbm.gnu, but the module is not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/doit_cmd.py", line 190, in run
    return command.parse_execute(args)
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/cmd_base.py", line 580, in execute
    codec_cls=codec_cls)
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/dependency.py", line 503, in __init__
    self.backend = db_class(backend_name, codec=codec_cls())
  File "/Users/annebitran/nikola_env/lib/python3.7/site-packages/doit/dependency.py", line 171, in __init__
    raise DatabaseException(message)
doit.dependency.DatabaseException: db type is dbm.gnu, but the module is not available

Any idea ? Thanks a lot !!

**Comment by jkloetzke** [comment]
Looks like your new Python does not support the GNU DBM format any more after the upgrade.

NB: Please file the bug in the project that you're using (Nikola?). The bug, even though Bob also hit it in the past, is not related to this particular project at all.
