### ISSUE TITLE
bob crashs on jenkins abruptly while the future was running or pending

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#328]
Hey, 

the new version of bob crashs (_just on jenkins_ ... I guess it **depends on the sandbox**!!!!):

```
+ bob-audit-engine -D bob 0.17.0rc1 -D recipe sandbox::ubuntu-aarch64 -D package aarch64::jetsonagx/sandbox::ubuntu-aarch64 -D step src -D language bash -D jenkins-build-tag jenkins-aarch64-jetsonagx-avpsit-release-sandbox__ubuntu-aarch64-11 -D jenkins-node FDT-C-PCS-0004 -D jenkins-build-url http://build-c02.fdtech.intern:8080/job/aarch64-jetsonagx-avpsit-release-sandbox__ubuntu-aarch64/11/ --recipes '{"commit": "cd370abd95efafcad0276ce57d8e5134591deba5", "description": "cd370ab-dirty", "dir": ".", "dirty": true, "remotes": {"origin": "ssh://git@bitbucket.fdtech.intern:7999/fdt/fdt.bobrecipes.git"}, "type": "git"}' --env sandbox_ubuntu-aarch64_src_1-e8bf-2a96.env --scmEx url sandbox/ubuntu-aarch64/src/1-e8bf-2a96 ./ubuntu-bionic-arm64-rootfs.tgz '{"url": "http://fdt-c-pcs-0004.fdtech.intern/fileserver/ubuntu-bionic-arm64-rootfs.tgz"}' -o sandbox_ubuntu-aarch64_src_1-e8bf-2a96.json.gz cf3864c34161c959ccbfc457f926d8574702843f 7fbf4598cbc4b17b9db8c5dd352f0df60d99a93b 7fbf4598cbc4b17b9db8c5dd352f0df60d99a93b
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/forkserver.py", line 178, in main
    _serve_one(s, listener, alive_r, handler)
  File "/usr/lib/python3.5/multiprocessing/forkserver.py", line 212, in _serve_one
    code = spawn._main(child_r)
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 115, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.5/multiprocessing/spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/lib/python3.5/runpy.py", line 254, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/lib/python3.5/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/data/jenkins-slave/bob/bob-audit-engine", line 13, in <module>
    sys.exit(auditEngine())
  File "/mnt/data/jenkins-slave/bob/pym/bob/scripts.py", line 335, in auditEngine
    with EventLoopWrapper() as loop:
  File "/mnt/data/jenkins-slave/bob/pym/bob/utils.py", line 585, in __init__
    multiprocessing.set_start_method('forkserver')
  File "/usr/lib/python3.5/multiprocessing/context.py", line 231, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
Traceback (most recent call last):
  File "/mnt/data/jenkins-slave/bob/bob-audit-engine", line 13, in <module>
    sys.exit(auditEngine())
  File "/mnt/data/jenkins-slave/bob/pym/bob/scripts.py", line 335, in auditEngine
    with EventLoopWrapper() as loop:
  File "/mnt/data/jenkins-slave/bob/pym/bob/utils.py", line 587, in __init__
    executor.submit(dummy).result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE
```

**Comment by mahaase** [comment]
btw. why the bob version will not shown correctly?

> bob-audit-engine -D bob 0.16.1.dev152+g81227c2

**Comment by jkloetzke** [comment]
Wow. This one took me quite a while to find the culprit. This python stuff is sometimes very surprising.

**Comment by jkloetzke** [comment]
I will certainly cut a 0.17-rc2 at the end of the week...

**Comment by mahaase** [comment]
> 
> 
> Wow. This one took me quite a while to find the culprit. This python stuff is sometimes very surprising.

U know, Im just searching for the really hard ones for u :)
It runs, again. Thx! 👍
