### ISSUE TITLE
Internal exception during build

### ISSUE THREAD

**Issue by Ferruck** [BobBuildTool/bob#329]
I was greeted with the following exception while building with `bob build -fbj ...`:

```
Bob version 0.17.0rc1
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/bob/invoker.py", line 154, in __getSandboxHelperPath
    from .develop.make import makeSandboxHelper
ModuleNotFoundError: No module named 'bob.develop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/bob/scripts.py", line 141, in catchErrors
    ret = fun(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/bob/scripts.py", line 242, in cmd
    ret = cmd(args.args, bobRoot)
  File "/usr/lib/python3.8/site-packages/bob/scripts.py", line 24, in __build
    doBuild(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/bob/cmds/build/build.py", line 258, in doBuild
    commonBuildDevelop(parser, argv, bobRoot, False)
  File "/usr/lib/python3.8/site-packages/bob/cmds/build/build.py", line 212, in commonBuildDevelop
    builder.cook(backlog, True if args.build_mode == 'checkout-only' else False)
  File "/usr/lib/python3.8/site-packages/bob/cmds/build/builder.py", line 658, in cook
    raise MultiBobError(self.__buildErrors)
  File "/usr/lib/python3.8/site-packages/bob/errors.py", line 51, in __init__
    raise i
  File "/usr/lib/python3.8/site-packages/bob/cmds/build/builder.py", line 562, in __taskWrapper
    ret = await coro()
  File "/usr/lib/python3.8/site-packages/bob/cmds/build/builder.py", line 714, in _cookStep
    await self._cookCheckoutStep(step, depth)
  File "/usr/lib/python3.8/site-packages/bob/cmds/build/builder.py", line 859, in _cookCheckoutStep
    await self._runShell(checkoutStep, "checkout", a)
  File "/usr/lib/python3.8/site-packages/bob/cmds/build/builder.py", line 488, in _runShell
    ret = await invoker.executeStep(InvocationMode.CALL, cleanWorkspace)
  File "/usr/lib/python3.8/site-packages/bob/invoker.py", line 319, in executeStep
    cmdArgs = self.__getSandboxCmds(tmpDir)
  File "/usr/lib/python3.8/site-packages/bob/invoker.py", line 261, in __getSandboxCmds
    cmdArgs = [ self.__getSandboxHelperPath() ]
  File "/usr/lib/python3.8/site-packages/bob/invoker.py", line 159, in __getSandboxHelperPath
    sandboxHelper = shutil.which("bob-namespace-sandbox")
NameError: name 'shutil' is not defined
```

**Comment by mahaase** [comment]
also depending on sandbox, like my issue https://github.com/BobBuildTool/bob/issues/328.
maybe this is one bug at all?!

**Comment by Ferruck** [comment]
I'm by far no Python expert but those backtraces look rather different to me... 🤔 We'll see what @jkloetzke has to say.

**Comment by mahaase** [comment]
I know, had also checked them, but the root the same, should that be a mere chance? maybe.. :)

**Comment by jkloetzke** [comment]
These are unrelated issues. But this one here was very easy... :grinning:
