### ISSUE TITLE
Bob crashes on old files

### ISSUE THREAD

**Issue by rhubert** [BobBuildTool/bob#370]
```
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.17.3.dev82+g7c547fe
Traceback (most recent call last):
  File "/home/ralf/projects/bob/pym/bob/scripts.py", line 147, in catchErrors
    ret = fun(*args, **kwargs)
  File "/home/ralf/projects/bob/pym/bob/scripts.py", line 248, in cmd
    ret = cmd(args.args, bobRoot)
  File "/home/ralf/projects/bob/pym/bob/scripts.py", line 29, in __develop
    doDevelop(*args, **kwargs)
  File "/home/ralf/projects/bob/pym/bob/cmds/build/build.py", line 284, in doDevelop
    commonBuildDevelop(parser, argv, bobRoot, True)
  File "/home/ralf/projects/bob/pym/bob/cmds/build/build.py", line 234, in commonBuildDevelop
    builder.cook(backlog, True if args.build_mode == 'checkout-only' else False)
  File "/home/ralf/projects/bob/pym/bob/cmds/build/builder.py", line 767, in cook
    raise self.__buildErrors[0]
  File "/home/ralf/projects/bob/pym/bob/cmds/build/builder.py", line 661, in __taskWrapper
    ret = await coro()
  File "/home/ralf/projects/bob/pym/bob/cmds/build/builder.py", line 826, in _cookStep
    await self._cookBuildStep(step, checkoutOnly, depth)
  File "/home/ralf/projects/bob/pym/bob/cmds/build/builder.py", line 1058, in _cookBuildStep
    buildHash = hashWorkspace(buildStep)
  File "/home/ralf/projects/bob/pym/bob/cmds/build/builder.py", line 53, in hashWorkspace
    os.path.join(step.getWorkspacePath(), "..", "cache.bin"))
  File "/home/ralf/projects/bob/pym/bob/utils.py", line 456, in hashDirectory
    return DirHasher(index, ignoreDirs).hashDirectory(path)
  File "/home/ralf/projects/bob/pym/bob/utils.py", line 436, in hashDirectory
    return self.__hashDir(os.fsencode(path))
  File "/home/ralf/projects/bob/pym/bob/utils.py", line 426, in __hashDir
    for (e, f, s) in entries
  File "/home/ralf/projects/bob/pym/bob/utils.py", line 426, in <listcomp>
    for (e, f, s) in entries
  File "/home/ralf/projects/bob/pym/bob/utils.py", line 364, in __hashEntry
    digest = self.__index.check(prefix, entry, s, hashFile)
  File "/home/ralf/projects/bob/pym/bob/utils.py", line 336, in check
    self.__writeEntry(name, st, digest)
  File "/home/ralf/projects/bob/pym/bob/utils.py", line 315, in __writeEntry
    digest, len(name)))
struct.error: argument out of range
```

```yaml
root: True

checkoutScript: |
   echo "foo" > foo
   tar --mtime='1970-01-01' -czf foo.tgz foo

buildScript: |
   tar xzf $1/foo.tgz

packageScript: |
   true
```

**Comment by rhubert** [comment]
```
$ stat -c "%y"  dev/build/crash/1/workspace/foo 
1970-01-01 00:00:00.000000000 +0100

dev/build/crash/1/workspace$ python3 -c "import os; print(os.lstat('foo'));"
os.stat_result(st_mode=33188, st_ino=270794, st_dev=65026, st_nlink=1, st_uid=1000, st_gid=1000, st_size=4, st_atime=1601623698, st_mtime=-3600, st_ctime=1601623698)
```

st_mtime is negative :thinking:

**Comment by Ferruck** [comment]
That's probably because of your timezone. Could you try setting your TZ to UTC?

**Comment by jkloetzke** [comment]
Looks like the 70s are calling. :laughing: We have to make the field a signed 64 bit int. And while at it we should get rid of `float2ns` by using the `st_*_ns` fields. This will save us from floating point rounding errors.
