### ISSUE TITLE
MSYS2 jenkins: "/bin/bash" not found

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#386]
Hi.

```
Baue auf Master in Arbeitsbereich E:\J\workspace\ros-d-toolchain__cmake-win64
[ros-d-toolchain__cmake-win64] $ /bin/bash -xe C:\Users\jenkins\AppData\Local\Temp\jenkins4997659751081406425.sh
The system cannot find the file specified
FATAL: Befehlsausführung fehlgeschlagen
java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
Caused: java.io.IOException: Cannot run program "/bin/bash" (in directory "E:\J\workspace\ros-d-toolchain__cmake-win64"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
```

older jobs stats with:
`#!bash -xe`
new:
`#!/bin/bash -xe`
breaks MSYS2 builds.

**Comment by mahaase** [comment]
MSYS2 has a /bin/bash.
But I guess, calling "/bin/bash" will generally not work for windows. We just can call a tool, which have to be in PATH.

**Comment by mahaase** [comment]
4 years ago... so i guess something is changed in our system. but what?

```
    def getShebang(self, windows, errexit=True):
        if windows:
            ret = "#!bash -x"
        else:
            ret = "#!/bin/bash -x"
        if errexit:
            ret += "e"
        return ret
```

**Comment by mahaase** [comment]
FUCK stupid!

our fault.... use -w for windows - hmh? sorry!
