### ISSUE TITLE
type object '_asyncio.Task' has no attribute 'current_task'

### ISSUE THREAD

**Issue by daxcore** [BobBuildTool/bob#391]
```
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.18.2.dev32+gb243d3e
Traceback (most recent call last):
  File "/home/daxcore/bob/pym/bob/scripts.py", line 147, in catchErrors
    ret = fun(*args, **kwargs)
  File "/home/daxcore/bob/pym/bob/scripts.py", line 248, in cmd
    ret = cmd(args.args, bobRoot)
  File "/home/daxcore/bob/pym/bob/scripts.py", line 29, in __develop
    doDevelop(*args, **kwargs)
  File "/home/daxcore/bob/pym/bob/cmds/build/build.py", line 288, in doDevelop
    commonBuildDevelop(parser, argv, bobRoot, True)
  File "/home/daxcore/bob/pym/bob/cmds/build/build.py", line 238, in commonBuildDevelop
    builder.cook(backlog, True if args.build_mode == 'checkout-only' else False)
  File "/home/daxcore/bob/pym/bob/cmds/build/builder.py", line 782, in cook
    raise self.__buildErrors[0]
  File "/home/daxcore/bob/pym/bob/cmds/build/builder.py", line 672, in __taskWrapper
    task = asyncio.Task.current_task()
AttributeError: type object '_asyncio.Task' has no attribute 'current_task'
```

https://docs.python.org/3/library/asyncio-task.html#task-object

without the `Task` it works for me- just: `task = asyncio.current_task()`

**Comment by jkloetzke** [comment]
Hmm, it took me a while but this is on Python 3.9, isn't it?

**Comment by daxcore** [comment]
yep. correct: https://archlinux.org/packages/extra/x86_64/python/ --> currently 3.9.1

**Comment by jkloetzke** [comment]
Ok, the API was deprecated in 3.7 and was then removed in 3.9 for no (obvious) good reason. :angry: I'll add a workaround...
