### ISSUE TITLE
AttributeError: 'Invoker' object has no attribute 'runInExecutor'

### ISSUE THREAD

**Issue by mahaase** [BobBuildTool/bob#444]
```
+ cat
[x86_64-linux-ros-devel__make-1] $ /bin/bash -xe /tmp/jenkins13896070620728198174.sh
+ bob _invoke devel_make_x86_64-linux-gnu_build_1-9f10-2cd4.spec.json fingerprint
+ bob _invoke devel_make_x86_64-linux-gnu_dist_1-9f10-2cd4.spec.json fingerprint
[x86_64-linux-ros-devel__make-1] $ /bin/bash -xe /tmp/jenkins4316098702045346596.sh
+ '[' -e .state/devel_make_src_2-9f10-2cd4.canary ']'
++ cat .state/devel_make_src_2-9f10-2cd4.canary
+ [[ d82bb4166c79d07cfcc3026ba737099f829fb13c != d82bb4166c79d07cfcc3026ba737099f829fb13c ]]
+ bob _invoke devel_make_src_2-9f10-2cd4.spec.json -vv
+ <wget> http://fdt-c-vm-0053.fdtech.intern/fs/gnu/make/make-4.3.tar.gz > ./make-4.3.tar.gz
Error: Recipe devel::make, layer basement in checkoutSCM: dir:., url:http://fdt-c-vm-0053.fdtech.intern/fs/gnu/make/make-4.3.tar.gz in checkoutSCM: dir:., url:http://fdt-c-vm-0053.fdtech.intern/fs/gnu/make/make-4.3.tar.gz failed
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Bob version 0.19.2.dev83+gef63b7d
Traceback (most recent call last):
  File "/opt/bob-next/pym/bob/scripts.py", line 153, in catchErrors
    ret = fun(*args, **kwargs)
  File "/opt/bob-next/pym/bob/scripts.py", line 254, in cmd
    ret = cmd(args.args, bobRoot)
  File "/opt/bob-next/pym/bob/scripts.py", line 109, in __invoke
    return doInvoke(*args, **kwargs)
  File "/opt/bob-next/pym/bob/cmds/invoke.py", line 59, in doInvoke
    args.clean, args.keep_sandbox))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/opt/bob-next/pym/bob/invoker.py", line 373, in executeStep
    await scm.invoke(self)
  File "/opt/bob-next/pym/bob/scm/url.py", line 309, in invoke
    err = await invoker.runInExecutor(UrlScm._download, self, destination)
AttributeError: 'Invoker' object has no attribute 'runInExecutor'
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE
```

on current bob master.

**Comment by jkloetzke** [comment]
Seems to be a regression from the Python 3.10 compatibility fixes. What's even more troublesome is that we don't seem to have tests for the URL SCM... :roll_eyes:
