### ISSUE TITLE
errors on mingw

### ISSUE THREAD

**Issue by rahu** [BobBuildTool/bob#5]
Since there are several path-name problems using bob on in a cygwin bash I'm currently trying to get bob running in a mingw-bash. 

```
>> root
>> root/lib
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Traceback (most recent call last):
  File "C:/projects/bob/pym\bob\cmds\build.py", line 846, in commonBuildDevelop
    prettyResultPath = builder.cook([package.getPackageStep()], package)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 549, in cook
    ret = self._cookPackageStep(step, done, depth)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 719, in _cookPackageStep
    self.cook(packageStep.getAllDepSteps(), packageStep.getPackage(), done, depth+1)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 546, in cook
    self._cookBuildStep(step, done, depth)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 623, in _cookBuildStep
    self.cook(buildStep.getAllDepSteps(), buildStep.getPackage(), done, depth+1)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 549, in cook
    ret = self._cookPackageStep(step, done, depth)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 680, in _cookPackageStep
    BobState().setDirectoryState(prettyPackagePath, packageDigest)
  File "C:/projects/bob/pym\bob\state.py", line 131, in setDirectoryState
    self.__save()
  File "C:/projects/bob/pym\bob\state.py", line 69, in __save
    os.rename(tmpFile, self.__path)
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: '.bob-state.pickle.new' -> '.bob-state.pickle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/projects/bob/pym\bob\scrips.py", line 79, in bob
    availableCommands[verb][0](recipes, argv, bobRoot)
  File "C:/projects/bob/pym\bob\scrips.py", line 30, in __develop
    doDevelop(*args, **kwargs)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 864, in doDevelop
    commonBuildDevelop(recipes, parser, argv, bobRoot, True)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 849, in commonBuildDevelop
    builder.saveBuildState()
  File "C:/projects/bob/pym\bob\cmds\build.py", line 361, in saveBuildState
    BobState().setBuildState(dict(self.__wasRun))
  File "C:/projects/bob/pym\bob\state.py", line 188, in setBuildState
    self.__save()
  File "C:/projects/bob/pym\bob\state.py", line 69, in __save
    os.rename(tmpFile, self.__path)
FileExistsError: [WinError 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist: '.bob-state.pickle.new' -> '.bob-state.pickle'

```

**Comment by rahu** [comment]
``` 
>> root
>> root/lib
   CHECKOUT  dev/src/lib/1/workspace
An internal Exception has occured. This should not have happenend.
Please open an issue at https://github.com/BobBuildTool/bob with the following backtrace:
Traceback (most recent call last):
  File "C:/projects/bob/pym\bob\scrips.py", line 79, in bob
    availableCommands[verb][0](recipes, argv, bobRoot)
  File "C:/projects/bob/pym\bob\scrips.py", line 30, in __develop
    doDevelop(*args, **kwargs)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 864, in doDevelop
    commonBuildDevelop(recipes, parser, argv, bobRoot, True)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 846, in commonBuildDevelop
    prettyResultPath = builder.cook([package.getPackageStep()], package)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 549, in cook
    ret = self._cookPackageStep(step, done, depth)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 719, in _cookPackageStep
    self.cook(packageStep.getAllDepSteps(), packageStep.getPackage(), done, depth+1)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 546, in cook
    self._cookBuildStep(step, done, depth)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 623, in _cookBuildStep
    self.cook(buildStep.getAllDepSteps(), buildStep.getPackage(), done, depth+1)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 549, in cook
    ret = self._cookPackageStep(step, done, depth)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 719, in _cookPackageStep
    self.cook(packageStep.getAllDepSteps(), packageStep.getPackage(), done, depth+1)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 546, in cook
    self._cookBuildStep(step, done, depth)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 623, in _cookBuildStep
    self.cook(buildStep.getAllDepSteps(), buildStep.getPackage(), done, depth+1)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 543, in cook
    self._cookCheckoutStep(step, done, depth)
  File "C:/projects/bob/pym\bob\cmds\build.py", line 604, in _cookCheckoutStep
    self._runShell(checkoutStep, "checkout")
  File "C:/projects/bob/pym\bob\cmds\build.py", line 506, in _runShell
    proc = subprocess.Popen(cmdLine, cwd=step.getWorkspacePath(), env=runEnv)
  File "C:/msys64/mingw64/lib/python3.5\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:/msys64/mingw64/lib/python3.5\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

```
