### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by louliang** [BobBuildTool/bob#562]
bob dev demo-cortex-r52 -j
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/forkserver.py", line 207, in main
    with socket.socket(socket.AF_UNIX, fileno=listener_fd) as listener, \
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 22] Invalid argument

Bob version 0.24.0
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/bob/scripts.py", line 146, in catchErrors
    ret = fun(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/bob/scripts.py", line 254, in cmd
    ret = cmd(args.args, bobRoot)
  File "/root/.local/lib/python3.8/site-packages/bob/scripts.py", line 29, in __develop
    doDevelop(*args, **kwargs)
  File "/root/.local/lib/python3.8/site-packages/bob/cmds/build/build.py", line 410, in doDevelop
    commonBuildDevelop(parser, argv, bobRoot, True)
  File "/root/.local/lib/python3.8/site-packages/bob/cmds/build/build.py", line 221, in commonBuildDevelop
    with EventLoopWrapper() as (loop, executor):
  File "/root/.local/lib/python3.8/site-packages/bob/utils.py", line 730, in __init__
    self.__executor = getProcessPoolExecutor()
  File "/root/.local/lib/python3.8/site-packages/bob/utils.py", line 714, in getProcessPoolExecutor
    executor.submit(dummy).result()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 645, in submit
    self._start_queue_management_thread()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 584, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 608, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.8/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.8/multiprocessing/popen_forkserver.py", line 59, in _launch
    self.pid = forkserver.read_signed(self.sentinel)
  File "/usr/lib/python3.8/multiprocessing/forkserver.py", line 334, in read_signed
    raise EOFError('unexpected EOF')
EOFError: unexpected EOF

**Comment by jkloetzke** [comment]
This looks like something is really broken in your environment. Somehow unix domain sockets do not seem to work. Could you provide some more information about your OS environment (Linux version, architecture, ...) and the steps to reproduce the issue?

**Comment by jkloetzke** [comment]
Ah, you're using WSL. This suspiciously looks like https://github.com/microsoft/WSL/issues/3935. Which WSL version are you using? It looks like you need to use WSL 2 for full Python compatibility.

**Comment by jkloetzke** [comment]
I believe this problem has been be fixed in git master with the above commit. In any case, please reopen if you still have trouble.
